# -*- coding: utf-8 -*-
"""IOT_VERSION 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CqFNkMjCly8kQeSqCAzW7kTLByyOd-tb
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

# Path to the CSV file (NOT just the folder)
data_path = "/content/drive/MyDrive/iot_data/aved_raw.csv"

data = pd.read_csv(data_path)

data.head()

import os

print(os.path.exists(data_path))

csv_path = "/content/drive/MyDrive/iot_data/aved_raw.csv"

# ==============================
# COMPLETE DATA PREPROCESSING
# FOR TRANSFORMER + MPC (WWTP)
# ==============================

import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler

# -------- USER SETTINGS --------
CSV_PATH = "/content/drive/MyDrive/iot_data/aved_raw.csv"   # upload this to Colab
T = 30   # past window (minutes)
H = 10   # prediction horizon (minutes)

# -------- 1. LOAD DATA --------
df = pd.read_csv(CSV_PATH)

# Convert time
df["time"] = pd.to_datetime(df["time"])
df = df.set_index("time")

# -------- 2. KEEP ONLY VALUE COLUMNS --------
value_cols = [c for c in df.columns if c.endswith("value")]
df = df[value_cols]

# -------- 3. REMOVE INVALID PLACEHOLDER CODES --------
invalid_codes = [1222, 2221, 2121, 0]
df = df.replace(invalid_codes, np.nan)

# -------- 4. FORWARD FILL & DROP REMAINING NaNs --------
df = df.ffill().dropna()

# -------- 5. DEFINE VARIABLES --------
state_cols = [
    "BIOLOGY.LINE 3 TANK 1.NH4 value",
    "BIOLOGY.LINE 3 TANK 1.NO3 value",
    "BIOLOGY.LINE 3 TANK 1.O2 value",
    "BIOLOGY.LINE 3 TANK 1.PO4 value",
    "BIOLOGY.LINE 3 TANK 1.SS value",
    "BIOLOGY.LINE 3 TANK 1.TEMPERATURE value",
    "BIOLOGY.LINE 3 TANK 2.O2 value",
    "BIOLOGY.LINE 3 TANK 2.SS value",
    "BIOLOGY.LINE 3 TANK 2.TEMPERATURE value"
]

control_cols = [
    "BIOLOGY.BLOWERSTATION 1.Q.AIRFLOW value",
    "BIOLOGY.LINE 3 TANK 1.Q.AIRFLOW value",
    "BIOLOGY.LINE 3 TANK 2.Q.AIRFLOW value",
    "BIOLOGY.LINE 3 TANK 1.O2.SETPOINT value",
    "BIOLOGY.LINE 3 TANK 2.O2.SETPOINT value",
    "BIOLOGY.LINE 3 TANK 1 VALVE 1.PCT value",
    "BIOLOGY.LINE 3 TANK 2 VALVE 1.PCT value"
]

disturbance_cols = [
    "INLET.Q value",
    "INLET.STATE.SWM INLET FLOW value"
]

# Combine all inputs
Z = df[state_cols + control_cols + disturbance_cols]

# -------- 6. NORMALIZATION --------
scaler = StandardScaler()
Z_scaled = scaler.fit_transform(Z)

# Save normalization for Simulink
np.save("scaler_mean.npy", scaler.mean_)
np.save("scaler_std.npy", scaler.scale_)

# -------- 7. CREATE TRANSFORMER SEQUENCES --------
def create_sequences(data, T, H, n_states):
    X, Y = [], []
    for i in range(len(data) - T - H):
        X.append(data[i:i+T])
        Y.append(data[i+T:i+T+H, :n_states])
    return np.array(X), np.array(Y)

X, Y = create_sequences(
    Z_scaled,
    T=T,
    H=H,
    n_states=len(state_cols)
)

# -------- 8. FINAL OUTPUT --------
print("✅ Preprocessing complete")
print(f"X shape (Transformer input): {X.shape}")
print(f"Y shape (Prediction target): {Y.shape}")
print("Scaler parameters saved for Simulink")

#----------------------------------------------
# -------- 9. SAVE PROCESSED DATA --------
np.save("X_transformer_input.npy", X)
np.save("Y_transformer_target.npy", Y)

print("✅ Files saved:")
print(" - X_transformer_input.npy")
print(" - Y_transformer_target.npy")
print(" - scaler_mean.npy")
print(" - scaler_std.npy")

from google.colab import files

files.download("X_transformer_input.npy")
files.download("Y_transformer_target.npy")
files.download("scaler_mean.npy")
files.download("scaler_std.npy")

# =====================================================
# TRANSFORMER TRAINING + SEPARATE TEST EVALUATION
# WWTP + MPC (FINAL CLEAN VERSION)
# =====================================================

import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import DataLoader, TensorDataset
from sklearn.metrics import mean_squared_error, r2_score
import matplotlib.pyplot as plt

# -----------------------
# 1. LOAD FULL DATA (~700k)
# -----------------------
X_all = np.load("X_transformer_input.npy")
Y_all = np.load("Y_transformer_target.npy")

print("Total samples:", len(X_all))

# -----------------------
# 2. DEFINE TRAIN & TEST
# -----------------------
TRAIN_SIZE = 200000   # ✅ UPDATED
TEST_SIZE  = 20000    # ✅ UPDATED

X_train = X_all[:TRAIN_SIZE]
Y_train = Y_all[:TRAIN_SIZE]

X_test = X_all[TRAIN_SIZE:TRAIN_SIZE+TEST_SIZE]
Y_test = Y_all[TRAIN_SIZE:TRAIN_SIZE+TEST_SIZE]

print("Train:", X_train.shape)
print("Test :", X_test.shape)

# -----------------------
# 3. TORCH DATASET
# -----------------------
X_train = torch.from_numpy(X_train).float()
Y_train = torch.from_numpy(Y_train).float()

train_loader = DataLoader(
    TensorDataset(X_train, Y_train),
    batch_size=64,
    shuffle=True,
    num_workers=2,
    pin_memory=True
)

# -----------------------
# 4. TRANSFORMER MODEL
# -----------------------
class WWTPTransformer(nn.Module):
    def __init__(self, input_dim, d_model=64,
                 nhead=4, layers=3,
                 horizon=10, n_states=9):

        super().__init__()

        self.horizon = horizon
        self.n_states = n_states

        self.embedding = nn.Linear(input_dim, d_model)

        encoder_layer = nn.TransformerEncoderLayer(
            d_model=d_model,
            nhead=nhead,
            batch_first=True
        )

        self.encoder = nn.TransformerEncoder(
            encoder_layer, layers
        )

        self.fc = nn.Linear(d_model,
                            horizon*n_states)

    def forward(self, x):
        x = self.embedding(x)
        x = self.encoder(x)
        x = x[:, -1, :]
        x = self.fc(x)
        return x.view(-1,
                      self.horizon,
                      self.n_states)

model = WWTPTransformer(
    input_dim=X_all.shape[2],
    horizon=Y_all.shape[1],
    n_states=Y_all.shape[2]
)

# -----------------------
# 5. TRAINING SETUP
# -----------------------
device = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

print("Using:", device)

model.to(device)
optimizer = torch.optim.Adam(
    model.parameters(), lr=1e-3
)
criterion = nn.MSELoss()

EPOCHS = 50

# -----------------------
# 6. TRAIN MODEL
# -----------------------
model.train()

for epoch in range(EPOCHS):

    epoch_loss = 0

    for xb, yb in train_loader:

        xb = xb.to(device)
        yb = yb.to(device)

        optimizer.zero_grad()

        pred = model(xb)
        loss = criterion(pred, yb)

        loss.backward()
        optimizer.step()

        epoch_loss += loss.item()

    print(f"Epoch {epoch+1}/{EPOCHS} "
          f"| Loss {epoch_loss/len(train_loader):.6f}")

# -----------------------
# 7. SAVE MODEL
# -----------------------
torch.save(
    model.state_dict(),
    "wwtp_transformer_model.pth"
)

print("✅ Model Saved")

# =====================================================
# 8. TEST EVALUATION (UNSEEN DATA)
# =====================================================

model.eval()

X_test = torch.from_numpy(X_test).float().to(device)
Y_test = torch.from_numpy(Y_test).float().to(device)

with torch.no_grad():
    Y_pred = model(X_test)

Y_pred = Y_pred.cpu().numpy()
Y_true = Y_test.cpu().numpy()

# -----------------------
# METRICS
# -----------------------
mse = mean_squared_error(
    Y_true.reshape(-1, Y_true.shape[-1]),
    Y_pred.reshape(-1, Y_pred.shape[-1])
)

rmse = np.sqrt(mse)

r2 = r2_score(
    Y_true.reshape(-1, Y_true.shape[-1]),
    Y_pred.reshape(-1, Y_pred.shape[-1])
)

print("\n📊 TEST PERFORMANCE")
print("RMSE:", rmse)
print("R² :", r2)

# -----------------------
# VISUALIZATION (NH4 example)
# -----------------------
state_idx = 0

plt.figure(figsize=(10,4))
plt.plot(Y_true[:200,0,state_idx], label="True")
plt.plot(Y_pred[:200,0,state_idx], label="Predicted")

plt.title("Model Prediction (Unseen Test Data)")
plt.legend()
plt.grid()
plt.show()

# =====================================================
# FULL MODEL EVALUATION
# =====================================================

import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

model.eval()

# ---- Prediction ----
with torch.no_grad():
    Y_pred = model(X_test)

Y_pred = Y_pred.cpu().numpy()
Y_true = Y_test.cpu().numpy()

# =====================================================
# PERFORMANCE METRICS
# =====================================================

mse = mean_squared_error(
    Y_true.reshape(-1, Y_true.shape[-1]),
    Y_pred.reshape(-1, Y_pred.shape[-1])
)

rmse = np.sqrt(mse)

mae = mean_absolute_error(
    Y_true.reshape(-1, Y_true.shape[-1]),
    Y_pred.reshape(-1, Y_pred.shape[-1])
)

r2 = r2_score(
    Y_true.reshape(-1, Y_true.shape[-1]),
    Y_pred.reshape(-1, Y_pred.shape[-1])
)

print("📊 MODEL PERFORMANCE")
print(f"MSE  : {mse:.6f}")
print(f"RMSE : {rmse:.6f}")
print(f"MAE  : {mae:.6f}")
print(f"R²   : {r2:.4f}")

state_idx = 0   # NH4
timestep = 0

plt.figure(figsize=(10,4))
plt.plot(Y_true[:200, timestep, state_idx], label="True")
plt.plot(Y_pred[:200, timestep, state_idx], label="Predicted")

plt.title("NH4 Prediction (Transformer)")
plt.xlabel("Time steps")
plt.ylabel("NH4")
plt.legend()
plt.grid()
plt.show()

state_map = {
    "NH4": 0,
    "NO3": 1,
    "O2": 2,
    "PO4": 3,
    "SS": 4
}

states_to_plot = ["NO3", "O2", "PO4", "SS"]
timestep = 0

plt.figure(figsize=(12,8))

for i, state in enumerate(states_to_plot):
    plt.subplot(2,2,i+1)

    idx = state_map[state]

    plt.plot(Y_true[:200, timestep, idx], label="True")
    plt.plot(Y_pred[:200, timestep, idx], label="Predicted")

    plt.title(f"{state} Prediction")
    plt.xlabel("Time step")
    plt.ylabel(state)
    plt.legend()
    plt.grid()

plt.tight_layout()
plt.show()

alpha = 1.42

COD_true = alpha * Y_true[:, timestep, state_map["SS"]]
COD_pred = alpha * Y_pred[:, timestep, state_map["SS"]]

BOD_true = 0.65 * COD_true
BOD_pred = 0.65 * COD_pred

plt.figure(figsize=(12,4))

# COD
plt.subplot(1,2,1)
plt.plot(COD_true[:200], label="True COD")
plt.plot(COD_pred[:200], label="Predicted COD")
plt.title("COD (Computed from SS)")
plt.xlabel("Time step")
plt.ylabel("COD")
plt.legend()
plt.grid()

# BOD
plt.subplot(1,2,2)
plt.plot(BOD_true[:200], label="True BOD")
plt.plot(BOD_pred[:200], label="Predicted BOD")
plt.title("BOD (Computed from COD)")
plt.xlabel("Time step")
plt.ylabel("BOD")
plt.legend()
plt.grid()

plt.tight_layout()
plt.show()

# ===============================
# LOAD TRAINED MODEL FOR MPC
# ===============================

model = WWTPTransformer(
    input_dim=X_all.shape[2],
    horizon=Y_all.shape[1],
    n_states=Y_all.shape[2]
)

model.load_state_dict(
    torch.load("wwtp_transformer_model.pth")
)

model.to(device)
model.eval()

print("✅ Transformer loaded for MPC")

'''CONTROL_INDEX = 12
NH4_INDEX = 0
SS_INDEX  = 4'''

NH4_INDEX = 0
NO3_INDEX = 1
O2_STATE_INDEX = 2   # dissolved oxygen STATE
PO4_INDEX = 3
SS_INDEX = 4

CONTROL_INDEX = 12

def mpc_cost(u, model, x0, device):

    x = x0.clone().to(device)

    total_cost = 0.0

    for t in range(len(u)):

        # apply control
        x[:, -1, CONTROL_INDEX] = float(u[t])

        with torch.no_grad():
            pred = model(x)

        nh4 = pred[:, :, NH4_INDEX]
        ss  = pred[:, :, SS_INDEX]

        COD = 1.42 * ss

        total_cost += (
    5.0 * torch.mean(nh4**2)        # strong NH4 control
    + 1.0 * torch.mean(COD**2)      # moderate COD
    + 0.05 * (u[t]**2)              # 🔥 REDUCE control penalty
)
        # get next state
        next_state = pred[:, 0, :]   # (1, 9)

        # shift window
        x = torch.roll(x, shifts=-1, dims=1)

        # ✅ FIX: update only state part
        x[:, -1, :9] = next_state

        # re-apply control
        x[:, -1, CONTROL_INDEX] = float(u[t])

    return total_cost.item()

state = X_test[0:1].clone().to(device)

!pip install scipy
from scipy.optimize import minimize

u0 = np.ones(10) * 2.0

result = minimize(
    mpc_cost,
    u0,
    args=(model, state, device),
    bounds=[(0.5,4)]*10,
    method="Powell",
    options={'maxiter': 50, 'disp': True}
)

optimal_O2 = result.x
print("Optimal O2:", optimal_O2)

mpc_steps = 50
HORIZON = 10

state = X_test[0:1].clone().to(device)

O2_history = []
NH4_history = []
SS_history = []
O2_state_history = []
for k in range(mpc_steps):

    res = minimize(
        mpc_cost,
        np.ones(HORIZON)*2.0,   # ✅ improved
        args=(model, state, device),
        bounds=[(0.5,4)]*HORIZON,   # ✅ fixed bounds
        method="Powell"
    )

    u_apply = res.x[0]
    O2_history.append(u_apply)

    # apply control
    state[:, -1, CONTROL_INDEX] = u_apply

    # predict next state
    with torch.no_grad():
        pred = model(state)

    next_states = pred[:,0,:]

    NH4_history.append(next_states[0, NH4_INDEX].item())
    SS_history.append(next_states[0, SS_INDEX].item())
    O2_state_history.append(next_states[0, O2_STATE_INDEX].item())

    # shift window
    state = torch.roll(state, shifts=-1, dims=1)

    # update state part
    state[:, -1, :next_states.shape[1]] = next_states

    # ✅ CRITICAL FIX: re-apply control
    state[:, -1, CONTROL_INDEX] = u_apply

print("✅ MPC finished")

import matplotlib.pyplot as plt

plt.figure(figsize=(14,8))

# ---- CONTROL ACTION ----
plt.subplot(2,2,1)
plt.plot(O2_history)
plt.title("MPC Control Input (O2 Setpoint)")
plt.xlabel("MPC Step")
plt.ylabel("Control")
plt.grid()

# ---- NH4 RESPONSE ----
plt.subplot(2,2,2)
plt.plot(NH4_history)
plt.title("NH4 Response under MPC")
plt.xlabel("MPC Step")
plt.ylabel("NH4")
plt.grid()

# ---- O2 STATE ----
plt.subplot(2,2,3)
plt.plot(O2_state_history)
plt.title("Dissolved O2 State")
plt.xlabel("MPC Step")
plt.ylabel("O2")
plt.grid()

# ---- SS RESPONSE ----
plt.subplot(2,2,4)
plt.plot(SS_history)
plt.title("SS Response under MPC")
plt.xlabel("MPC Step")
plt.ylabel("SS")
plt.grid()

plt.tight_layout()
plt.show()

!pip install onnx onnxscript
import torch

# make sure model is already on device
model.eval()

# ✅ FIX: move dummy input to device
dummy_input = torch.randn(1, X_all.shape[1], X_all.shape[2]).to(device)

torch.onnx.export(
    model,
    dummy_input,
    "transformer_model.onnx",
    input_names=['input'],
    output_names=['output'],
    opset_version=13,
    export_params=True
)

import os
print(os.listdir())

from google.colab import files
files.download("transformer_model.onnx")